"""empty message

Revision ID: d2174953e475
Revises: 
Create Date: 2023-02-28 15:35:11.496068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2174953e475'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    user_table=op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('confirm_password', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    
    op.create_table('post',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('body', sa.String(length=1000), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    # ### end Alembic commands ###

    op.bulk_insert(user_table,
    [
        {'name':'shreyas',
         'email':'shreyas12@gmail.com',
         'password':'$5$rounds=535000$0SN7918qy4cJZn5N$N3HgzdUvYu/nDKZ30Vpf9EdcCIfgk0Ry2YFIoBYx6B.',
         'confirm_password':'$5$rounds=535000$0SN7918qy4cJZn5N$N3HgzdUvYu/nDKZ30Vpf9EdcCIfgk0Ry2YFIoBYx6B.'},
        {
        "name":"shreyas mohite",
        "email":"shreyas123@gmail.com",
        "password":"$5$rounds=535000$p9xUaYtgt8W0lUHI$WUM9Roqct7fvUNa3KnBgggituWNdcMkW6jOr4jGymr7",
        "confirm_password":"$5$rounds=535000$p9xUaYtgt8W0lUHI$WUM9Roqct7fvUNa3KnBgggituWNdcMkW6jOr4jGymr7"}
    ])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    op.drop_table('user')
    # ### end Alembic commands ###
